cirrus audio dlkm: Fix build error
There was the below error log output. the module cirrus_cs35l45 should
depend on the cirrus_wm_adsp. If the cirrus_wm_adsp had not been built
firstly. This error happend.

FAILED: out/target/product/dubai/obj/vendor/cirrus/audio/dlkm/sound/soc/codecs/buildko.timestamp

ERROR: "wm_adsp_fw_enum" [../../vendor/cirrus/audio/dlkm/sound/soc/codecs/cirrus_cs35l45.ko] undefined!
ERROR: "wm_adsp2_component_remove" [../../vendor/cirrus/audio/dlkm/sound/soc/codecs/cirrus_cs35l45.ko] undefined!

Change-Id: Ifcbb59b338261b87405185d8bd8e3bcc8aca0c40
Signed-off-by: huangys <huangys@motorola.com>
Reviewed-on: https://gerrit.mot.com/1779446
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Guobin Zhang <zhanggb@motorola.com>
Submit-Approved: Jira Key