cs35l41: Fix the build error of user release
devm_kstrdup_const has not been added to Google abi kernel whietelist.
use devm_kstrdup to instead

ERROR: "devm_kstrdup_const" [../../vendor/cirrus/audio/dlkm/sound/soc/codecs/cirrus_cs35l41.ko] undefined!

Change-Id: I2a6d86aa9da4673b209032403955358a6f1dd22a
Signed-off-by: huangys <huangys@motorola.com>
Reviewed-on: https://gerrit.mot.com/1784516
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Reviewed-by: Guobin Zhang <zhanggb@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key