Fix compilation errors for Olson R upgrade
Build errors fixed:
- vendor/cirrus/audio/dlkm/sound/soc/codecs/cs35l35.c:921:6: warning:
    variable 'ret' is used uninitialized whenever 'if' condition
    is false [-Wsometimes-uninitialized]
- vendor/cirrus/audio/dlkm/sound/soc/codecs/cs35l35.c:1477:3: warning:
    misleading indentation; statement is not part of the previous
    'for' [-Wmisleading-indentation]
- vendor/cirrus/audio/dlkm/drivers/extcon/extcon-madera.c:141:51:
    warning: unused variable 'cs47l92_hpdet_ranges'
    [-Wunused-const-variable]
- vendor/cirrus/audio/dlkm/drivers/extcon/extcon-madera.c:489:38:
    warning: unused variable 'cs47l92_hp_tuning'
    [-Wunused-const-variable]

Change-Id: I6c6bcb43d2669a3cf30adb32b8caff9829caf7e1
Reviewed-on: https://gerrit.mot.com/1884018
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Ravikumar Vembu <raviv@motorola.com>
Submit-Approved: Jira Key